pipeline {
    agent {
        docker {
            image 'docker:24.0.2-dind'
            args '-u root --privileged -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    environment {
        COMPOSE_PROJECT_NAME = 'springboot-mysql-app'
    }

    stages {
        stage('Install Tools') {
            steps {
                sh '''
                apk add --no-cache openjdk17 maven docker-compose
                '''
            }
        }

        stage('Build JAR') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Start App with Docker Compose') {
            steps {
                sh 'docker-compose down || true'
                sh 'docker-compose up --build -d'
            }
        }
    }

    post {
        always {
            echo "App and MySQL containers deployed with docker-compose."
        }
    }
}
